import type { PostReadingSettings } from "./types";

export const DEFAULT_SETTINGS: PostReadingSettings = {
  enabled: true,
  speed: 1,
  volume: 1,
  voiceURI: null,
  autoVoice: true,
  ttsEngine: "web-speech",
  customTtsEndpoint: null,
  customTtsTimingMode: "engine",
  autoplayNext: true,
  autoplayMode: "autoscroll",
  skipPromotedPosts: true,
  endOfTweetDing: true,
  includeQuotes: true,
  fetchFullQuotes: true,
  fullQuoteDisplay: "scroll",
  includeHyperlinks: false,
  includeImageAltText: true,
  includeImageOcr: true,
  includeLinkPreviews: true,
  expandShowMore: true,
  activeTweetHighlight: true,
  bodyHighlightMode: "smooth",
  playerPosition: "top-right",
  buttonPlacement: "auto",
  useHandles: false,
  keyNextTweet: "Ctrl+Alt+ArrowDown",
  keyPreviousTweet: "Ctrl+Alt+ArrowUp",
  keyNextChunk: "Ctrl+Alt+ArrowRight",
  keyPreviousChunk: "Ctrl+Alt+ArrowLeft",
  keySkipOcr: "Ctrl+Alt+S",
  keyPlayPause: "Ctrl+Alt+\\",
};
